import { Category, Gig, Testimonial } from "./types";

export const categories: Category[] = [
  { id: "c1", name: "Smart Contract Development", icon: "Code", slug: "smart-contracts", gigCount: 1240 },
  { id: "c2", name: "dApp & Web3 Frontend", icon: "Globe", slug: "web3-frontend", gigCount: 980 },
  { id: "c3", name: "Web3 Design & UI/UX", icon: "Palette", slug: "web3-design", gigCount: 670 },
  { id: "c4", name: "Tokenomics & Research", icon: "BarChart", slug: "tokenomics", gigCount: 420 },
  { id: "c5", name: "Crypto Content & Copywriting", icon: "PenTool", slug: "crypto-content", gigCount: 890 },
  { id: "c6", name: "Community & DAO Operations", icon: "Users", slug: "community-dao", gigCount: 760 },
  { id: "c7", name: "NFT Art & Digital Collectibles", icon: "Image", slug: "nft-art", gigCount: 580 },
  { id: "c8", name: "Crypto Marketing & Growth", icon: "TrendingUp", slug: "crypto-marketing", gigCount: 710 },
  { id: "c9", name: "On-chain Analytics", icon: "Activity", slug: "onchain-analytics", gigCount: 310 },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Elena Voss",
    role: "Founder & CEO",
    company: "Aether Protocol",
    avatar: "https://i.pravatar.cc/64?img=47",
    quote: "Workfolio helped us find an exceptional smart contract engineer. The work was delivered to the highest standard and ahead of schedule.",
    rating: 5,
  },
  {
    id: "t2",
    name: "Marcus Hale",
    role: "Head of Growth",
    company: "Nexus Labs",
    avatar: "https://i.pravatar.cc/64?img=32",
    quote: "The community management team we hired through Workfolio scaled our Discord from 2k to 28k engaged members in under 90 days.",
    rating: 5,
  },
  {
    id: "t3",
    name: "Sofia Patel",
    role: "Product Lead",
    company: "Lumina DAO",
    avatar: "https://i.pravatar.cc/64?img=40",
    quote: "Outstanding tokenomics work. Clear, well-researched, and directly helped us secure our seed round. Highly recommended.",
    rating: 5,
  },
];

export const gigs: Gig[] = [
  {
    id: "g1",
    title: "Custom Smart Contract Development (Solidity / Rust)",
    shortDesc: "Secure, audited smart contracts for tokens, NFTs, and protocols",
    fullDesc: "I design and develop secure, gas-optimized smart contracts tailored to your protocol requirements. Experienced with ERC standards, upgradeable patterns, and cross-chain deployments. All contracts include detailed documentation and test coverage.",
    category: "Smart Contract Development",
    seller: {
      id: "s1",
      name: "Alex Rivera",
      avatar: "https://i.pravatar.cc/64?img=15",
      level: "Top Rated",
      rating: 4.98,
      reviewCount: 312,
      location: "Lisbon, Portugal",
      memberSince: "2021",
      responseTime: "1 hour",
    },
    startingPrice: 28,
    rating: 4.98,
    reviewCount: 312,
    deliveryDays: 7,
    images: [
      "https://picsum.photos/id/1015/800/600",
      "https://picsum.photos/id/160/800/600",
      "https://picsum.photos/id/201/800/600",
    ],
    tags: ["Solidity", "Smart Contracts", "Security"],
    packages: [
      {
        name: "Basic",
        price: 28,
        deliveryDays: 7,
        description: "Single standard contract (ERC-20 / ERC-721)",
        features: ["1 contract", "Basic unit tests", "Deployment script", "2 rounds of revisions"],
        revisions: 2,
      },
      {
        name: "Standard",
        price: 52,
        deliveryDays: 10,
        description: "Protocol-grade contracts with documentation",
        features: ["Up to 3 contracts", "Comprehensive test suite", "NatSpec documentation", "Gas optimization", "4 revisions"],
        revisions: 4,
      },
      {
        name: "Premium",
        price: 95,
        deliveryDays: 14,
        description: "Full protocol development + audit coordination",
        features: ["Complete system architecture", "Upgradeable contracts", "Full test coverage + fuzzing", "Audit preparation support", "Unlimited revisions (14 days)"],
        revisions: 999,
      },
    ],
    faqs: [
      { q: "Do you provide post-deployment support?", a: "Yes, Premium packages include 30 days of support and monitoring." },
      { q: "Can you work with existing codebases?", a: "Absolutely. I regularly audit and extend existing protocols." },
    ],
  },
  {
    id: "g2",
    title: "Full-Stack Web3 dApp Development",
    shortDesc: "Production-ready dApps with wallet integration and on-chain logic",
    fullDesc: "I build complete decentralized applications from frontend to smart contracts. Strong focus on user experience, security, and scalability. Experienced with Next.js, wagmi, viem, and The Graph.",
    category: "dApp & Web3 Frontend",
    seller: {
      id: "s2",
      name: "Liam Chen",
      avatar: "https://i.pravatar.cc/64?img=28",
      level: "Top Rated",
      rating: 4.96,
      reviewCount: 187,
      location: "Singapore",
      memberSince: "2020",
      responseTime: "2 hours",
    },
    startingPrice: 45,
    rating: 4.96,
    reviewCount: 187,
    deliveryDays: 12,
    images: [
      "https://picsum.photos/id/20/800/600",
      "https://picsum.photos/id/180/800/600",
      "https://picsum.photos/id/251/800/600",
    ],
    tags: ["Next.js", "wagmi", "dApp"],
    packages: [
      { name: "Basic", price: 45, deliveryDays: 12, description: "Frontend + 2 smart contract integrations", features: ["Wallet connection", "Read/write contract functions", "Responsive UI", "Basic deployment"], revisions: 2 },
      { name: "Standard", price: 78, deliveryDays: 16, description: "Full-featured dApp with indexing", features: ["Full frontend + backend logic", "The Graph subgraph", "Transaction history", "Advanced UI components"], revisions: 4 },
      { name: "Premium", price: 128, deliveryDays: 21, description: "Enterprise-grade dApp with ongoing support", features: ["Complete architecture", "Multi-chain support", "Analytics dashboard", "3 months maintenance"], revisions: 6 },
    ],
    faqs: [],
  },
  {
    id: "g3",
    title: "Premium Web3 UI/UX Design & Prototyping",
    shortDesc: "High-end interface design for protocols and dApps",
    fullDesc: "I create sophisticated, intuitive interfaces for Web3 products. From DAO dashboards to NFT marketplaces, every design is built with user trust and clarity in mind. Deliverables include Figma files, interactive prototypes, and developer handoff specifications.",
    category: "Web3 Design & UI/UX",
    seller: {
      id: "s3",
      name: "Isabella Moreau",
      avatar: "https://i.pravatar.cc/64?img=40",
      level: "Top Rated",
      rating: 4.97,
      reviewCount: 241,
      location: "Paris, France",
      memberSince: "2021",
      responseTime: "3 hours",
    },
    startingPrice: 25,
    rating: 4.97,
    reviewCount: 241,
    deliveryDays: 6,
    images: [
      "https://picsum.photos/id/29/800/600",
      "https://picsum.photos/id/160/800/600",
    ],
    tags: ["UI/UX", "Figma", "Web3 Design"],
    packages: [
      { name: "Basic", price: 25, deliveryDays: 6, description: "Core screens + prototype", features: ["6-8 high-fidelity screens", "Interactive prototype", "Basic design system", "2 revision rounds"], revisions: 2 },
      { name: "Standard", price: 48, deliveryDays: 9, description: "Complete product design system", features: ["12-15 screens", "Full component library", "Dark + light modes", "Developer specs"], revisions: 4 },
      { name: "Premium", price: 85, deliveryDays: 12, description: "End-to-end design + user research", features: ["Full product design", "Usability testing (5 users)", "Design system + tokens", "Ongoing design partnership"], revisions: 6 },
    ],
    faqs: [],
  },
  {
    id: "g4",
    title: "Tokenomics Design & Economic Modeling",
    shortDesc: "Sustainable token models and incentive structures",
    fullDesc: "I develop comprehensive tokenomics frameworks for protocols and DAOs. This includes supply mechanics, utility design, vesting schedules, emissions curves, and governance modeling. All deliverables come with clear documentation and simulation models.",
    category: "Tokenomics & Research",
    seller: {
      id: "s4",
      name: "Dr. Julian Park",
      avatar: "https://i.pravatar.cc/64?img=12",
      level: "Level 2",
      rating: 4.93,
      reviewCount: 94,
      location: "Seoul, South Korea",
      memberSince: "2022",
      responseTime: "4 hours",
    },
    startingPrice: 38,
    rating: 4.93,
    reviewCount: 94,
    deliveryDays: 8,
    images: ["https://picsum.photos/id/201/800/600"],
    tags: ["Tokenomics", "Economics", "Research"],
    packages: [
      { name: "Basic", price: 38, deliveryDays: 8, description: "Core token model + documentation", features: ["Token utility design", "Supply & allocation model", "Basic vesting schedule", "Written report"], revisions: 2 },
      { name: "Standard", price: 9800, deliveryDays: 11, description: "Full economic model with simulations", features: ["Dynamic emissions modeling", "Incentive alignment analysis", "Governance framework", "Monte Carlo simulations"], revisions: 4 },
      { name: "Premium", price: 16500, deliveryDays: 16, description: "Institutional-grade tokenomics + advisory", features: ["Complete economic architecture", "Stress testing & scenarios", "Investor deck materials", "30-day advisory support"], revisions: 6 },
    ],
    faqs: [],
  },
  {
    id: "g5",
    title: "High-Impact Crypto Copywriting & Whitepapers",
    shortDesc: "Persuasive, technically accurate content for Web3 projects",
    fullDesc: "I craft premium copy and long-form content that resonates with both technical and institutional audiences. Experienced with litepapers, pitch decks, website copy, and investor communications for protocols raising significant capital.",
    category: "Crypto Content & Copywriting",
    seller: {
      id: "s5",
      name: "Olivia Grant",
      avatar: "https://i.pravatar.cc/64?img=39",
      level: "Top Rated",
      rating: 4.95,
      reviewCount: 176,
      location: "London, UK",
      memberSince: "2020",
      responseTime: "2 hours",
    },
    startingPrice: 22,
    rating: 4.95,
    reviewCount: 176,
    deliveryDays: 5,
    images: ["https://picsum.photos/id/180/800/600", "https://picsum.photos/id/251/800/600"],
    tags: ["Copywriting", "Whitepaper", "Content"],
    packages: [
      { name: "Basic", price: 22, deliveryDays: 5, description: "Core website + landing page copy", features: ["Homepage & key pages", "Product descriptions", "SEO-optimized structure", "2 revision rounds"], revisions: 2 },
      { name: "Standard", price: 6800, deliveryDays: 8, description: "Litepaper + full brand narrative", features: ["Full litepaper (15-20 pages)", "Technical overview", "Token & governance sections", "Pitch deck narrative"], revisions: 4 },
      { name: "Premium", price: 11500, deliveryDays: 12, description: "Complete content system + strategy", features: ["Whitepaper / litepaper", "Full website copy", "Investor materials", "Content strategy framework"], revisions: 6 },
    ],
    faqs: [],
  },
  {
    id: "g6",
    title: "DAO Operations & Community Management",
    shortDesc: "Build and scale engaged Web3 communities",
    fullDesc: "I help DAOs and crypto projects build sustainable, high-engagement communities. Services include governance process design, moderator training, proposal management, and long-term community strategy.",
    category: "Community & DAO Operations",
    seller: {
      id: "s6",
      name: "Theo Nakamura",
      avatar: "https://i.pravatar.cc/64?img=25",
      level: "Top Rated",
      rating: 4.91,
      reviewCount: 203,
      location: "Tokyo, Japan",
      memberSince: "2021",
      responseTime: "1 hour",
    },
    startingPrice: 19,
    rating: 4.91,
    reviewCount: 203,
    deliveryDays: 7,
    images: ["https://picsum.photos/id/29/800/600", "https://picsum.photos/id/160/800/600"],
    tags: ["DAO", "Community", "Governance"],
    packages: [
      { name: "Basic", price: 2900, deliveryDays: 7, description: "Community setup + moderation framework", features: ["Discord/Telegram structure", "Role & permission design", "Moderator guidelines", "30-day support"], revisions: 2 },
      { name: "Standard", price: 6200, deliveryDays: 14, description: "Full community operations", features: ["Governance process design", "Proposal templates", "Weekly reporting", "3 months management"], revisions: 4 },
      { name: "Premium", price: 9800, deliveryDays: 21, description: "DAO operations partnership", features: ["End-to-end governance system", "Delegate program design", "Quarterly strategy", "Dedicated support"], revisions: 6 },
    ],
    faqs: [],
  },
  {
    id: "g7",
    title: "Premium NFT Collection Design & Smart Contracts",
    shortDesc: "End-to-end NFT projects from concept to mint",
    fullDesc: "I design and develop complete NFT collections, including generative artwork, smart contracts with advanced features (reveals, royalties, staking), and minting platforms. All work is production-ready and audit-friendly.",
    category: "NFT Art & Digital Collectibles",
    seller: {
      id: "s7",
      name: "Camille Laurent",
      avatar: "https://i.pravatar.cc/64?img=44",
      level: "Level 2",
      rating: 4.94,
      reviewCount: 138,
      location: "Montreal, Canada",
      memberSince: "2022",
      responseTime: "3 hours",
    },
    startingPrice: 32,
    rating: 4.94,
    reviewCount: 138,
    deliveryDays: 10,
    images: ["https://picsum.photos/id/201/800/600", "https://picsum.photos/id/180/800/600"],
    tags: ["NFT", "Generative Art", "Smart Contracts"],
    packages: [
      { name: "Basic", price: 4800, deliveryDays: 10, description: "Smart contracts + basic artwork", features: ["ERC-721 + ERC-1155 contracts", "Basic generative script", "Metadata structure", "Minting page"], revisions: 2 },
      { name: "Standard", price: 9200, deliveryDays: 16, description: "Full collection with custom artwork", features: ["5,000+ unique pieces", "Advanced contract features", "Reveal mechanism", "Custom mint site"], revisions: 4 },
      { name: "Premium", price: 16800, deliveryDays: 24, description: "Complete NFT ecosystem", features: ["Full generative system", "Staking & utility contracts", "Marketplace integration", "Launch strategy support"], revisions: 6 },
    ],
    faqs: [],
  },
  {
    id: "g8",
    title: "Strategic Crypto Marketing & Growth",
    shortDesc: "Data-driven growth for Web3 projects",
    fullDesc: "I develop and execute growth strategies for crypto protocols and DAOs. Focus areas include narrative development, KOL partnerships, content distribution, and community-led acquisition — all executed with transparency and measurable KPIs.",
    category: "Crypto Marketing & Growth",
    seller: {
      id: "s8",
      name: "Daniel Kim",
      avatar: "https://i.pravatar.cc/64?img=8",
      level: "Top Rated",
      rating: 4.89,
      reviewCount: 165,
      location: "Dubai, UAE",
      memberSince: "2020",
      responseTime: "2 hours",
    },
    startingPrice: 30,
    rating: 4.89,
    reviewCount: 165,
    deliveryDays: 9,
    images: ["https://picsum.photos/id/180/800/600", "https://picsum.photos/id/251/800/600"],
    tags: ["Marketing", "Growth", "KOL"],
    packages: [
      { name: "Basic", price: 4500, deliveryDays: 9, description: "Growth audit + strategy", features: ["Current funnel analysis", "Positioning & messaging", "90-day growth roadmap", "KOL shortlist"], revisions: 2 },
      { name: "Standard", price: 8500, deliveryDays: 14, description: "Execution of core growth initiatives", features: ["Campaign management", "KOL coordination (10+)", "Content calendar", "Performance reporting"], revisions: 4 },
      { name: "Premium", price: 14200, deliveryDays: 21, description: "Full growth partnership", features: ["Multi-channel strategy", "Influencer program design", "Quarterly reviews", "Dedicated strategist"], revisions: 6 },
    ],
    faqs: [],
  },
];

// Helper functions
export function getGigById(id: string): Gig | undefined {
  return gigs.find((g) => g.id === id);
}

export function getGigsByCategory(categoryName: string): Gig[] {
  return gigs.filter((g) => g.category === categoryName);
}

export function searchGigs(query: string): Gig[] {
  const q = query.toLowerCase().trim();
  if (!q) return gigs;
  return gigs.filter(
    (g) =>
      g.title.toLowerCase().includes(q) ||
      g.shortDesc.toLowerCase().includes(q) ||
      g.tags.some((t) => t.toLowerCase().includes(q)) ||
      g.category.toLowerCase().includes(q) ||
      g.seller.name.toLowerCase().includes(q)
  );
}
